receivers:
  otlp:
    protocols:
      grpc:
        endpoint: '0.0.0.0:4317'
      http:
        endpoint: '0.0.0.0:4318'

#processors:
#  batch:

exporters:
  debug:
    verbosity: detailed
  #prometheus:
  #    endpoint: "localhost:8889"
  otlphttp:
    endpoint: "http://loki:3100/otlp"
  otlp:
    endpoint: tempo:4318
    tls:
      insecure: true



service:
  pipelines:
    metrics:
      receivers: [otlp]
      #processors: [batch]
      exporters: [debug] #,prometheus]
    traces:
      receivers: [otlp]
      exporters: [debug, otlp]
    logs:
      receivers: [otlp]
      exporters: [debug, otlphttp]